baseURL = 'https://ultrali.me/'
languageCode = 'zh-cn'
title = 'ultralime'
theme = "re-terminal"

[params]
    themeColor = "green"
    title = "ultralime"
    subtitle = ""
    owner = ""
    keywords = ""
    copyright = "&copy; 2024 Eltrac, All Rights Reserved"

    [params.Logo]
        logoText = "ultra-lime"
        logoHomeLink = "/"

[menu]
    [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    [[menu.main]]
    identifier = "blog"
    name = "极客死亡计划"
    url = "https://www.geedea.pro"
